- name: Configuração da minha VM
  hosts: vm
  become : yes

  tasks:

          - name: instalação de um servidor web
            apt: 
                name: apache2
           
          - name: instalação do vim
            shell: "apt install vim"
